export const QUARTIERS_OUAGADOUGOU = [
  "Ouaga 2000",
  "Zone du Bois",
  "Patte d'Oie",
  "Cissin",
  "Dassasgho",
  "Kalgondin",
  "Kossodo",
  "Tanghin",
  "Tampouy",
  "Somgandé",
  "Pissy",
  "Samandin",
  "Wemtenga",
  "Zogona",
  "Koulouba",
  "Gounghin",
  "Bilbalogho",
  "Dapoya",
  "Larlé",
  "Nemnin",
  "Nonsin",
  "Paspanga",
  "Saint-Léon",
  "Tiedpalogo",
  "Bendogo",
  "Kamboinsé",
  "Nioko 2",
  "Bassinko",
  "Zagtouli",
  "Karpala",
  "1200 Logements",
  "Kilwin",
  "Rimkieta",
  "Wayalghin",
  "Silmandé",
  "Paglayiri",
  "Kamboinsin",
  "Saaba",
  "Koubri"
];

export const PRIX_PAR_TYPE = {
  "Documents": 500,
  "Petit colis": 1000,
  "Colis moyen": 1500,
  "Gros colis": 2500,
  "Nourriture": 1000,
  "Autre": 1500,
};